### PR TITLE
#168662049 - Retrieve a user's requests

### PR DESCRIPTION
**Pull request by OlawaleJoseph**
#### What does this PR do?
  Enables users to retrieve all requests made

#### Description of Task to be completed?
  - Ensure only users with a requester role can access this endpoint.
  - Ensure a requester can only see requests made by him/ her

#### How should this be manually tested?
  - git clone this repo using the command `git clone git@github.com:andela/firestar-backend.git`
  - cd to the project
  - checkout to the branch using the command `git checkout ft-request-table-168662049`
  - create a `.env` file and set PORT,JWT_SECRET and DB variables as specified in the .env.example file.
  - Run the command `npm install` in the terminal.
  - Open a terminal and run `npm test`.
  - Open a terminal and run `npm run migrate:dev` and `npm run seed:dev`
  1. Open Postman, make a post request to `localhost:<port>/api/v1/users/auth/login`, with any of the below 
            in the request body.
- `{email: requester1@gmail.com, password: Password1$}`
2. Copy the token in the reponse
3. Make a POST request to `http:localhost:<port>/api/v1/requests` with the token obtained above in the request header as `authorization`=`Bearer <token obtained>`
 4. Send a request object containing the following for a one-way trip:
         `{
           reason: 'Business',
           departmentId: 2,
           tripType: 'oneWay',
        }`
       Change the tripType to `return` or `multiCity` to create return trip or muliti-city Trip. Note the request id sent in the response.
5. Make a GET request to `http:localhost:<port>/api/v1/requests` with the token obatained above in the request header as `authorization = Bearer <token>` 

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#168662049](https://www.pivotaltracker.com/story/show/168662049)

#### Screenshots (if appropriate)
Code Coverage
Screenshot (93)

Request made with PostMan
Screenshot (94)

#### Questions:
N/A

### CODE REVIEW

**Comment by zanio** [comment]
Please fix conflict

**Comment by OlawaleJoseph** [comment]
> Please fix conflict

Done

**Comment by zanio** [comment]
> > Please fix conflict
> 
> Done

I am currently testing locally

**Comment by zanio** [comment]
Great Job bro.

**Pull request merged**
