### PR TITLE
#168662048 Builds sign in with Facebook and google

### PR DESCRIPTION
**Pull request by zanio**
#### What does this PR do?
IT signs user in with facebook and google
#### Description of Task to be completed?
None
#### How should this be manually tested?
1. ```git clone https://github.com/Devs-AA/Barefoot.git```  and checkout into ft-logout-168662046 branch
2. run `npm install` and create  a `.env file` with the key value pair as specified on the `.env.example` file
3. run `npm run migrate:dev` and `npm run seed:dev`

4. Visit the route `http://localhost:3300/api/v1/users/auth/token/google?access_token=${process.env.access_token_google}` where access_token is the user token which is generated from the client side and sent to the backend. If it is correct the user should be logged in and data saved in the database. Use the access_token from the `.env.example`

REPEAT THE SAME PROCEDURE FOR THE ROUTE
`http://localhost:3300/api/v1/users/auth/token/google?access_token=${process.env.access_token_facebook}` but this time around with an env value of access_token_facebook

None
#### What are the relevant pivotal tracker stories?
[#168662048](https://www.pivotaltracker.com/story/show/#168662046)

#### Screenshots (if appropriate)

image

Test coverage:

image

#### Questions:

### CODE REVIEW

**Comment by OlawaleJoseph** [comment]
Also, Travis build is failing. You can check the details to know the cause of the error and how to fix it.

**Comment by zanio** [comment]
> How do I generate `access_token_google` and `access_token_facebook`

Those values are sent from the frontend to the backend. According to google docs and passport. When we get the token from the frontend we also want to do how verification before inserting the user into the table. For this purpose i am currently using my own access token which i generated from the frontend through a script. I don't know if you get the concept ?

**Comment by OlawaleJoseph** [comment]
> > How do I generate `access_token_google` and `access_token_facebook`
> 
> Those values are sent from the frontend to the backend. According to google docs and passport. When we get the token from the frontend we also want to do how verification before inserting the user into the table. For this purpose i am currently using my own access token which i generated from the frontend through a script. I don't know if you get the concept ?

I do, but how do I test?

**Comment by zanio** [comment]
Please see this article for the full explanation. 
https://medium.com/@alexanderleon/implement-social-authentication-with-react-restful-api-9b44f4714fa

**Comment by zanio** [comment]
> > > How do I generate `access_token_google` and `access_token_facebook`
> > 
> > 
> > Those values are sent from the frontend to the backend. According to google docs and passport. When we get the token from the frontend we also want to do how verification before inserting the user into the table. For this purpose i am currently using my own access token which i generated from the frontend through a script. I don't know if you get the concept ?
> 
> I do, but how do I test?

Oh okay. Please check the team thread

**Comment by OlawaleJoseph** [comment]
> Please see this article for the full explanation.
> https://medium.com/@alexanderleon/implement-social-authentication-with-react-restful-api-9b44f4714fa

I see. so no way to test for that without getting the token from either google or facebook, right?

**Pull request merged**
