### PR TITLE
#167730740 Restore email service to project

### PR DESCRIPTION
**Pull request by zanio**
#### What does this PR do?
Restore email service to the project
#### Description of Task to be completed?
None
#### How should this be manually tested?
1. ```git clone https://github.com/Devs-AA/Barefoot.git```  
2. run `npm install` and create  a `.env file` with the key value pair as specified on the `.env.example` file
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
Not Applicable to this ticket.

#### Screenshots (if appropriate)
Test coverage:

image

#### Questions:

### CODE REVIEW

**Comment by OlawaleJoseph** [comment]
Good work @zanio 

I tried registering and didn't get an email verification. Below is a screenshot of what I received, which is the old thing we had.
Screenshot (87)

**Comment by zanio** [comment]
> Good work @zanio
> 
> I tried registering and didn't get an email verification. Below is a screenshot of what I received, which is the old thing we had.
> Screenshot (87)

@OlawaleJoseph  have you set the env variable ?

**Comment by OlawaleJoseph** [comment]
> > Good work @zanio
> > I tried registering and didn't get an email verification. Below is a screenshot of what I received, which is the old thing we had.
> > Screenshot (87)
> 
> @OlawaleJoseph have you set the env variable ?

Yes I did.
Without env variables I should get an error, right?

**Comment by zanio** [comment]
> > > Good work @zanio
> > > I tried registering and didn't get an email verification. Below is a screenshot of what I received, which is the old thing we had.
> > > Screenshot (87)
> > 
> > 
> > @OlawaleJoseph have you set the env variable ?
> 
> Yes I did.
> Without env variables I should get an error, right?

@OlawaleJoseph  
```
HOST_EMAIL
PORT_EMAIL
SECURE_EMAIL
PASSWORD_EMAIL
```

Do you have a value for those keys

**Comment by OlawaleJoseph** [comment]
> > > > Good work @zanio
> > > > I tried registering and didn't get an email verification. Below is a screenshot of what I received, which is the old thing we had.
> > > > Screenshot (87)
> > > 
> > > 
> > > @OlawaleJoseph have you set the env variable ?
> > 
> > 
> > Yes I did.
> > Without env variables I should get an error, right?
> 
> @OlawaleJoseph
> 
> ```
> HOST_EMAIL
> PORT_EMAIL
> SECURE_EMAIL
> PASSWORD_EMAIL
> ```
> 
> Do you have a value for those keys

I do

**Comment by OlawaleJoseph** [comment]
> > > > Good work @zanio
> > > > I tried registering and didn't get an email verification. Below is a screenshot of what I received, which is the old thing we had.
> > > > Screenshot (87)
> > > 
> > > 
> > > @OlawaleJoseph have you set the env variable ?
> > 
> > 
> > Yes I did.
> > Without env variables I should get an error, right?
> 
> @OlawaleJoseph
> 
> ```
> HOST_EMAIL
> PORT_EMAIL
> SECURE_EMAIL
> PASSWORD_EMAIL
> ```
> 
> Do you have a value for those keys

Looking at the user Controller there is no functionality
Screenshot (88)
 to send email

**Comment by zanio** [comment]
> > > > > Good work @zanio
> > > > > I tried registering and didn't get an email verification. Below is a screenshot of what I received, which is the old thing we had.
> > > > > Screenshot (87)
> > > > 
> > > > 
> > > > @OlawaleJoseph have you set the env variable ?
> > > 
> > > 
> > > Yes I did.
> > > Without env variables I should get an error, right?
> > 
> > 
> > @OlawaleJoseph
> > ```
> > HOST_EMAIL
> > PORT_EMAIL
> > SECURE_EMAIL
> > PASSWORD_EMAIL
> > ```
> > 
> > 
> > Do you have a value for those keys
> 
> I do

Please check your email. You should receive a signup verification email

**Comment by OlawaleJoseph** [comment]
> > > > > > Good work @zanio
> > > > > > I tried registering and didn't get an email verification. Below is a screenshot of what I received, which is the old thing we had.
> > > > > > Screenshot (87)
> > > > > 
> > > > > 
> > > > > @OlawaleJoseph have you set the env variable ?
> > > > 
> > > > 
> > > > Yes I did.
> > > > Without env variables I should get an error, right?
> > > 
> > > 
> > > @OlawaleJoseph
> > > ```
> > > HOST_EMAIL
> > > PORT_EMAIL
> > > SECURE_EMAIL
> > > PASSWORD_EMAIL
> > > ```
> > > 
> > > 
> > > Do you have a value for those keys
> > 
> > 
> > I do
> 
> Please check your email. You should receive a signup verification email

I just did again. No email

**Comment by zanio** [comment]
Give me a second let me check from my end

**Comment by zanio** [comment]
image

This is the message i got just now once i registered

**Comment by OlawaleJoseph** [comment]
> image
> 
> This is the message i got just now once i registered

Share a screenshot of yuor postman

**Comment by zanio** [comment]
image

**Comment by OlawaleJoseph** [comment]
Still the same issue

**Comment by zanio** [comment]
> Still the same issue

Can we have a sync ?

**Comment by zanio** [comment]
> > Still the same issue
> 
> Can we have a sync ?

https://zoom.us/j/7076005092

**Comment by OlawaleJoseph** [comment]
> > > Still the same issue
> > 
> > 
> > Can we have a sync ?
> 
> https://zoom.us/j/7076005092

I have joined

**Comment by OlawaleJoseph** [comment]
> > > > Still the same issue
> > > 
> > > 
> > > Can we have a sync ?
> > 
> > 
> > https://zoom.us/j/7076005092
> 
> I have joined

`{ Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:636:8) code: 'ESOCKET', command: 'CONN' }`

**Comment by zanio** [comment]
@OlawaleJoseph  Please can you pull, i have made an update to the mail class under the service.

**Comment by zanio** [comment]
> @OlawaleJoseph Please can you pull, i have made an update to the mail class under the service.

Please wait is the update ?

**Pull request merged**
